/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.*;
import javax.swing.JOptionPane;
import util.Koneksi;

/**
 *
 * @author Lenovo
 */
public class Action extends javax.swing.JFrame {
    Connection conn = (Connection) Koneksi.koneksiDB();

    /**
     * Creates new form Action
     */
    Home home;
    String id;
    
    public Action(Home home, String kondisi, String id) {
        initComponents();
        this.home = home;
        this.id = id;
        
     if(kondisi == "edit"){
         lb_action.setText("Edit Data");
         btn_save.setVisible(false);
         System.out.println(id);
         
     } else {
         lb_action.setText("Add Data");
         btn_update.setVisible(false);
         btn_delete.setVisible(false);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_action = new javax.swing.JLabel();
        lb_nama_barang = new javax.swing.JLabel();
        tf_nama_barang = new javax.swing.JTextField();
        lb_jumlah_barang = new javax.swing.JLabel();
        tf_jumlah_barang = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_action.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_action.setText("Action_Data");

        lb_nama_barang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nama_barang.setText("Nama Barang");

        lb_jumlah_barang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_jumlah_barang.setText("Jumlah Barang");

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_jumlah_barang)
                    .addComponent(tf_nama_barang)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nama_barang)
                            .addComponent(lb_jumlah_barang)
                            .addComponent(lb_action, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_action, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_nama_barang)
                .addGap(2, 2, 2)
                .addComponent(tf_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_jumlah_barang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_jumlah_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String namaBarang,jumlahBarang;
        namaBarang = tf_nama_barang.getText();
        jumlahBarang = tf_jumlah_barang.getText();
        
        if(namaBarang.isEmpty() || jumlahBarang.isEmpty()){
            JOptionPane.showMessageDialog(null, "tidak boleh kosong");
        }else {
            try {
                Statement st = conn.createStatement();
                String query = "INSERT INTO `barang`"
                        + "(`Nama_barang`, `Jumlah_barang`)"
                        + " VALUES ('"+  namaBarang +"','"+ jumlahBarang +"') ";
                st.executeUpdate(query);
                home.getData();
                dispose();
                
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
        
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
         String namaBarang, jumlahBarang, idBarang;
        
        namaBarang = tf_nama_barang.getText();
        jumlahBarang = tf_jumlah_barang.getText();
        idBarang = id;
        
        if (namaBarang.isEmpty() || jumlahBarang.isEmpty()){
            JOptionPane.showMessageDialog(null, "Tidak Boleh Kosong");
       
        } else {
            try {
                Statement st = conn.createStatement();
                String query = "UPDATE `barang` SET "
                        + "`Nama_barang`=' " + namaBarang + "',"
                        + "`Jumlah_barang`='" + jumlahBarang + "'"
                        + " WHERE `id` = '" + idBarang + "'";
                st.executeUpdate(query);
                
                home.getData();
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String idBaString;
        idBaString = id;
        int konfirmasi = JOptionPane.showConfirmDialog(null,
                "Apakah Anda Ingin Menghapus Data Ini?",
                "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == 0) {
            try {
            Statement st = conn.createStatement();
            String query = "DELETE FROM `barang` WHERE `Id`='"+idBaString+"' ";
            st.executeUpdate(query);
            
            home.getData();
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Action.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Action().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel lb_action;
    private javax.swing.JLabel lb_jumlah_barang;
    private javax.swing.JLabel lb_nama_barang;
    public javax.swing.JTextField tf_jumlah_barang;
    public javax.swing.JTextField tf_nama_barang;
    // End of variables declaration//GEN-END:variables
}
